name: Build And Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: "quay.io"
  DOCKER_NAMESPACE: "unstructured-io"
  IMAGE_PLATFORMS: linux/amd64
  PACKAGE: "unstructured-api"
  PIPELINE_PACKAGE: "general"
  PIP_VERSION: "22.2.1"
  BUILD_TYPE_TAG_SUFFIX: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Login to Quay.io
      #   uses: docker/login-action@v1
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.QUAY_IO_ROBOT_USERNAME }}
      #     password: ${{ secrets.QUAY_IO_ROBOT_TOKEN }}

      # TODO(rniko): add a step to test the built image before pushing. https://unstructured-ai.atlassian.net/browse/CORE-805
      - name: Build and push Docker image
        run: |
          VERSION=$(grep -m1 version preprocessing-pipeline-family.yaml | cut -d ' ' -f2)
          GIT_SHA=$(git rev-parse --short HEAD)
          IMAGE_NAME=${{ env.PACKAGE }}
          docker buildx build --platform=${{ env.IMAGE_PLATFORMS }} --provenance=false --push \
          --build-arg PIP_VERSION=${{ env.PIP_VERSION }} \
          --build-arg PIPELINE_PACKAGE=${{ env.PIPELINE_PACKAGE }} \
          --progress plain \
          -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${IMAGE_NAME}:${GIT_SHA} \
          -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${IMAGE_NAME}:${VERSION} \
          -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${IMAGE_NAME}:latest .
